# Generated by Django 5.2.8 on 2025-11-21 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_employee_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='name',
            new_name='employee_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
        migrations.AddField(
            model_name='employee',
            name='contact_type',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='contact_value',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='date_joined',
            field=models.DateField(default=1992),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admin',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('department_admin', 'Department Admin'), ('inventory_admin', 'Inventory Admin'), ('inventory_admin', 'Employee')], max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterModelTable(
            name='admin',
            table='account',
        ),
        migrations.AlterModelTable(
            name='employee',
            table='employee',
        ),
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('requisition_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_requested', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved_Dep', 'Approved_Dep'), ('Denied', 'Denied'), ('Forwarded_Inv', 'Forwarded_Inv')], default='Pending', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('admin_dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.admin')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.employee')),
            ],
            options={
                'db_table': 'requisition',
            },
        ),
        migrations.CreateModel(
            name='Requisition_Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.products')),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.requisition')),
            ],
            options={
                'db_table': 'requisition_item',
            },
        ),
    ]
