# Generated by Django 5.2.8 on 2025-11-22 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_employee_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('department_admin', 'Department Admin'), ('inventory_admin', 'Inventory Admin'), ('employee', 'Employee')], max_length=50),
        ),
        migrations.CreateModel(
            name='Inventory_Balance',
            fields=[
                ('balance_id', models.AutoField(primary_key=True, serialize=False)),
                ('unit', models.CharField(max_length=20)),
                ('opening_inventory', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantity_unit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantity_meters', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantity_klg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('min_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('procurement_suggestion', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.products')),
            ],
            options={
                'db_table': 'inventory_balance',
            },
        ),
    ]
