# Generated by Django 5.2.8 on 2025-11-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_admin_role_inventory_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
