# Generated by Django 5.2.8 on 2025-11-23 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_products_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='admin_id',
            new_name='acc_id',
        ),
        migrations.RemoveField(
            model_name='products',
            name='stock',
        ),
    ]
