# Generated by Django 5.2.8 on 2025-11-23 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_admin_id_admin_acc_id_remove_products_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisition',
            name='admin_dep',
        ),
    ]
