# Generated by Django 5.2.8 on 2025-11-23 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_requisition_admin_dep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='admin',
            field=models.ForeignKey(db_column='acc_id', on_delete=django.db.models.deletion.CASCADE, to='myapp.admin'),
        ),
    ]
