# Generated by Django 5.2.8 on 2025-11-23 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_employee_admin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inventory_Balance',
            new_name='InventoryBalance',
        ),
        migrations.CreateModel(
            name='StockIn',
            fields=[
                ('stock_in_id', models.AutoField(primary_key=True, serialize=False)),
                ('unit', models.CharField(max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_meters', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantity_klg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date_in', models.DateField()),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.admin')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.products')),
            ],
            options={
                'db_table': 'stock_in',
            },
        ),
        migrations.CreateModel(
            name='StockOut',
            fields=[
                ('stock_out_id', models.AutoField(primary_key=True, serialize=False)),
                ('unit', models.CharField(max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_meters', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantity_klg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date_out', models.DateField()),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.admin')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.products')),
            ],
            options={
                'db_table': 'stock_out',
            },
        ),
    ]
