# Generated by Django 5.2.8 on 2025-11-23 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_rename_inventory_balance_inventorybalance_stockin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockin',
            name='admin',
            field=models.ForeignKey(db_column='acc_id', on_delete=django.db.models.deletion.CASCADE, to='myapp.admin'),
        ),
    ]
