# Generated by Django 5.2.8 on 2025-11-23 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_stockin_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockin',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='stockout',
            name='admin',
        ),
        migrations.AddField(
            model_name='stockin',
            name='acc',
            field=models.ForeignKey(db_column='acc_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.admin'),
        ),
        migrations.AddField(
            model_name='stockout',
            name='acc',
            field=models.ForeignKey(db_column='acc_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.admin'),
        ),
    ]
