# Generated by Django 5.1.7 on 2025-11-30 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_stockin_admin_remove_stockout_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='status',
            field=models.CharField(choices=[('Pending Approval', 'Pending Approval'), ('Approved', 'Approved'), ('Partially Approved – Pending Purchase', 'Partially Approved – Pending Purchase'), ('Denied', 'Denied'), ('Pending Purchase', 'Pending Purchase'), ('Purchased', 'Purchased'), ('Ready for Pickup', 'Ready for Pickup')], default='Pending Approval', max_length=40),
        ),
    ]
