# Generated by Django 5.2.8 on 2025-11-30 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_products_stock_alter_requisition_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='admin_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requisition_item',
            name='approved_qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='requisition_item',
            name='purchase_qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
