# Generated by Django 5.2.8 on 2025-11-30 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_requisition_admin_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='status',
            field=models.CharField(choices=[('Pending Approval', 'Pending Approval'), ('Approved', 'Approved'), ('Partially Approved – Pending Purchase', 'Partially Approved – Pending Purchase'), ('Denied', 'Denied'), ('Pending Purchase', 'Pending Purchase'), ('Purchased', 'Purchased'), ('Ready for Pickup', 'Ready for Pickup')], default='Pending Approval', max_length=100),
        ),
    ]
