# Generated by Django 5.2.8 on 2025-11-30 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_requisition_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisitionStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=40, null=True)),
                ('new_status', models.CharField(max_length=40)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.admin')),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.requisition')),
            ],
        ),
    ]
