# Generated by Django 5.2.8 on 2025-11-30 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_requisitionstatushistory'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='requisitionstatushistory',
            table='requisition_status_history',
        ),
    ]
