# Generated by Django 5.2.8 on 2025-11-30 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_requisitionstatushistory_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisitionstatushistory',
            name='changed_by',
            field=models.ForeignKey(db_column='changed_by', on_delete=django.db.models.deletion.CASCADE, to='myapp.admin'),
        ),
        migrations.AlterModelTable(
            name='requisitionstatushistory',
            table='requisition_status_history',
        ),
    ]
