# Generated by Django 5.2.8 on 2025-11-30 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_alter_requisitionstatushistory_changed_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisitionstatushistory',
            name='id',
        ),
        migrations.AddField(
            model_name='requisitionstatushistory',
            name='history_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='requisitionstatushistory',
            name='changed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.admin'),
        ),
    ]
