# Generated by Django 5.2.8 on 2025-11-30 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_remove_requisitionstatushistory_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisitionstatushistory',
            name='changed_by',
            field=models.ForeignKey(db_column='changed_by', on_delete=django.db.models.deletion.CASCADE, to='myapp.admin'),
        ),
        migrations.AlterField(
            model_name='requisitionstatushistory',
            name='requisition',
            field=models.ForeignKey(db_column='requisition_id', on_delete=django.db.models.deletion.CASCADE, to='myapp.requisition'),
        ),
    ]
